[package]
name = "auxein"
description = "Std-only command-line interface for auxein-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true

[[bin]]
name = "auxein"
path = "src/main.rs"

[dependencies]
auxein-core = { version = "0.4.0", path = "../auxein-core" }
